version: "2.4"

services:
  connect:
    build:
      context: .
      target: dev
      dockerfile: ./connect.Dockerfile
    volumes:
      - ./src/.:/node/app
      - /node/app/node_modules
    env_file:
      - ./.env/app.env
